#普通数据的配置
name: zhangsan
#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing
#行内配置
student: {name: lisi,age: 18,addr: beijing}
#配置数据，集合 普通字符串
city:
  - beijing
  - tianjin
  - chongqing
  - shanghai
#city: [beijing,tianjin,chongqin,shanghai]
#配置数据，集合 对象数据
student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 17
    addr: tianjin
#map配置
map:
  key1: value1
  key2: value2


#student: [{name: tom,age: 18,addr: beijing},{name: tony,age: 20,addr: tianjin}]


#tomcat启动服务器端口号
server:
  port: 8081
  servlet:
    context-path: /demo #当前web应用的名称
